
export default class BibleService {

  async fetchScripture(book, chapter, verse = '', translation = 'web') {
      let query = `${book} ${chapter}`;
      if (verse) {
        query += `:${verse}`;
      }
      const url = `https://bible-api.com/${encodeURIComponent(query)}?translation=${translation}`;
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error('Failed to fetch Bible text');
      }

      const data = await response.json();
      return data;
  }

  TORAH_PORTIONS = [
    { name: "Bereshit",     ref: "Genesis 1",         book: "Genesis",      chapter: 1  },
    { name: "Noach",        ref: "Genesis 6",         book: "Genesis",      chapter: 6  },
    { name: "Lech-Lecha",   ref: "Genesis 12",        book: "Genesis",      chapter: 12 },
    { name: "Vayera",       ref: "Genesis 18",        book: "Genesis",      chapter: 18 },
    { name: "Chayei Sarah", ref: "Genesis 23",        book: "Genesis",      chapter: 23 },
    { name: "Toldot",       ref: "Genesis 25",        book: "Genesis",      chapter: 25 },
    { name: "Vayetzei",     ref: "Genesis 28",        book: "Genesis",      chapter: 28 },
    { name: "Vayishlach",   ref: "Genesis 32",        book: "Genesis",      chapter: 32 },
    { name: "Vayeshev",     ref: "Genesis 37",        book: "Genesis",      chapter: 37 },
    { name: "Miketz",       ref: "Genesis 41",        book: "Genesis",      chapter: 41 },
    { name: "Vayigash",     ref: "Genesis 44",        book: "Genesis",      chapter: 44 },
    { name: "Vayechi",      ref: "Genesis 47",        book: "Genesis",      chapter: 47 },
    { name: "Shemot",       ref: "Exodus 1",          book: "Exodus",       chapter: 1  },
    { name: "Vaera",        ref: "Exodus 6",          book: "Exodus",       chapter: 6  },
    { name: "Bo",           ref: "Exodus 10",         book: "Exodus",       chapter: 10 },
    { name: "Beshalach",    ref: "Exodus 13",         book: "Exodus",       chapter: 13 },
    { name: "Yitro",        ref: "Exodus 18",         book: "Exodus",       chapter: 18 },
    { name: "Mishpatim",    ref: "Exodus 21",         book: "Exodus",       chapter: 21 },
    { name: "Terumah",      ref: "Exodus 25",         book: "Exodus",       chapter: 25 },
    { name: "Tetzaveh",     ref: "Exodus 27",         book: "Exodus",       chapter: 27 },
    { name: "Ki Tisa",      ref: "Exodus 30",         book: "Exodus",       chapter: 30 },
    { name: "Vayakhel",     ref: "Exodus 35",         book: "Exodus",       chapter: 35 },
    { name: "Pekudei",      ref: "Exodus 38",         book: "Exodus",       chapter: 38 },
    { name: "Vayikra",      ref: "Leviticus 1",       book: "Leviticus",    chapter: 1  },
    { name: "Tzav",         ref: "Leviticus 6",       book: "Leviticus",    chapter: 6  },
    { name: "Shemini",      ref: "Leviticus 9",       book: "Leviticus",    chapter: 9  },
    { name: "Tazria",       ref: "Leviticus 12",      book: "Leviticus",    chapter: 12 },
    { name: "Metzora",      ref: "Leviticus 14",      book: "Leviticus",    chapter: 14 },
    { name: "Acharei Mot",  ref: "Leviticus 16",      book: "Leviticus",    chapter: 16 },
    { name: "Kedoshim",     ref: "Leviticus 19",      book: "Leviticus",    chapter: 19 },
    { name: "Emor",         ref: "Leviticus 21",      book: "Leviticus",    chapter: 21 },
    { name: "Behar",        ref: "Leviticus 25",      book: "Leviticus",    chapter: 25 },
    { name: "Bechukotai",   ref: "Leviticus 26",      book: "Leviticus",    chapter: 26 },
    { name: "Bamidbar",     ref: "Numbers 1",         book: "Numbers",      chapter: 1  },
    { name: "Nasso",        ref: "Numbers 4",         book: "Numbers",      chapter: 4  },
    { name: "Beha'alotcha", ref: "Numbers 8",         book: "Numbers",      chapter: 8  },
    { name: "Shelach",      ref: "Numbers 13",        book: "Numbers",      chapter: 13 },
    { name: "Korach",       ref: "Numbers 16",        book: "Numbers",      chapter: 16 },
    { name: "Chukat",       ref: "Numbers 19",        book: "Numbers",      chapter: 19 },
    { name: "Balak",        ref: "Numbers 22",        book: "Numbers",      chapter: 22 },
    { name: "Pinchas",      ref: "Numbers 25",        book: "Numbers",      chapter: 25 },
    { name: "Matot",        ref: "Numbers 30",        book: "Numbers",      chapter: 30 },
    { name: "Masei",        ref: "Numbers 33",        book: "Numbers",      chapter: 33 },
    { name: "Devarim",      ref: "Deuteronomy 1",     book: "Deuteronomy",  chapter: 1  },
    { name: "Vaetchanan",   ref: "Deuteronomy 3",     book: "Deuteronomy",  chapter: 3  },
    { name: "Eikev",        ref: "Deuteronomy 7",     book: "Deuteronomy",  chapter: 7  },
    { name: "Re'eh",        ref: "Deuteronomy 11",    book: "Deuteronomy",  chapter: 11 },
    { name: "Shoftim",      ref: "Deuteronomy 16",    book: "Deuteronomy",  chapter: 16 },
    { name: "Ki Teitzei",   ref: "Deuteronomy 21",    book: "Deuteronomy",  chapter: 21 },
    { name: "Ki Tavo",      ref: "Deuteronomy 26",    book: "Deuteronomy",  chapter: 26 },
    { name: "Nitzavim",     ref: "Deuteronomy 29",    book: "Deuteronomy",  chapter: 29 },
    { name: "Vayeilech",    ref: "Deuteronomy 31",    book: "Deuteronomy",  chapter: 31 },
    { name: "Ha'azinu",     ref: "Deuteronomy 32",    book: "Deuteronomy",  chapter: 32 },
    { name: "V'Zot HaBracha", ref: "Deuteronomy 33", book: "Deuteronomy",  chapter: 33 },
  ];

  getPortionIndexForDate(date) {
  const start = new Date(date.getFullYear(), 0, 1);
  const dayOfYear = Math.floor((date - start) / 86400000);
  return dayOfYear % this.TORAH_PORTIONS.length;
  }

  // ── Verse of the Day / Week ────────────────────────────────────────────────
  // Curated references in canonical order (Genesis → Revelation) so the
  // selection walks the whole Bible across the year. The verse text itself is
  // fetched at runtime through fetchScripture(), so it always matches the
  // translation the reader has selected. The index is derived purely from the
  // date, so everyone sees the same verse on a given day (or week).
  VERSES_OF_THE_DAY = [
    // Old Testament
    { book: 'Genesis', chapter: 1, verse: '1' },
    { book: 'Genesis', chapter: 1, verse: '27' },
    { book: 'Genesis', chapter: 1, verse: '31' },
    { book: 'Genesis', chapter: 2, verse: '24' },
    { book: 'Genesis', chapter: 3, verse: '15' },
    { book: 'Genesis', chapter: 8, verse: '22' },
    { book: 'Genesis', chapter: 9, verse: '16' },
    { book: 'Genesis', chapter: 12, verse: '2-3' },
    { book: 'Genesis', chapter: 15, verse: '6' },
    { book: 'Genesis', chapter: 28, verse: '15' },
    { book: 'Genesis', chapter: 50, verse: '20' },
    { book: 'Exodus', chapter: 3, verse: '14' },
    { book: 'Exodus', chapter: 6, verse: '7' },
    { book: 'Exodus', chapter: 14, verse: '14' },
    { book: 'Exodus', chapter: 15, verse: '2' },
    { book: 'Exodus', chapter: 15, verse: '11' },
    { book: 'Exodus', chapter: 20, verse: '12' },
    { book: 'Exodus', chapter: 33, verse: '14' },
    { book: 'Exodus', chapter: 34, verse: '6' },
    { book: 'Leviticus', chapter: 11, verse: '44' },
    { book: 'Leviticus', chapter: 19, verse: '18' },
    { book: 'Leviticus', chapter: 26, verse: '12' },
    { book: 'Numbers', chapter: 6, verse: '24-26' },
    { book: 'Numbers', chapter: 14, verse: '18' },
    { book: 'Numbers', chapter: 23, verse: '19' },
    { book: 'Deuteronomy', chapter: 4, verse: '29' },
    { book: 'Deuteronomy', chapter: 6, verse: '5' },
    { book: 'Deuteronomy', chapter: 6, verse: '6-7' },
    { book: 'Deuteronomy', chapter: 7, verse: '9' },
    { book: 'Deuteronomy', chapter: 8, verse: '3' },
    { book: 'Deuteronomy', chapter: 10, verse: '12' },
    { book: 'Deuteronomy', chapter: 30, verse: '19' },
    { book: 'Deuteronomy', chapter: 31, verse: '6' },
    { book: 'Deuteronomy', chapter: 31, verse: '8' },
    { book: 'Deuteronomy', chapter: 33, verse: '27' },
    { book: 'Joshua', chapter: 1, verse: '5' },
    { book: 'Joshua', chapter: 1, verse: '8' },
    { book: 'Joshua', chapter: 1, verse: '9' },
    { book: 'Joshua', chapter: 24, verse: '15' },
    { book: 'Judges', chapter: 6, verse: '12' },
    { book: 'Judges', chapter: 6, verse: '14' },
    { book: 'Ruth', chapter: 1, verse: '16' },
    { book: 'Ruth', chapter: 2, verse: '12' },
    { book: '1 Samuel', chapter: 2, verse: '2' },
    { book: '1 Samuel', chapter: 12, verse: '24' },
    { book: '1 Samuel', chapter: 16, verse: '7' },
    { book: '1 Samuel', chapter: 17, verse: '47' },
    { book: '2 Samuel', chapter: 7, verse: '22' },
    { book: '2 Samuel', chapter: 22, verse: '2-3' },
    { book: '2 Samuel', chapter: 22, verse: '31' },
    { book: '1 Kings', chapter: 8, verse: '23' },
    { book: '1 Kings', chapter: 8, verse: '56' },
    { book: '2 Kings', chapter: 6, verse: '16' },
    { book: '2 Kings', chapter: 19, verse: '19' },
    { book: '1 Chronicles', chapter: 16, verse: '11' },
    { book: '1 Chronicles', chapter: 16, verse: '34' },
    { book: '1 Chronicles', chapter: 29, verse: '11' },
    { book: '2 Chronicles', chapter: 7, verse: '14' },
    { book: '2 Chronicles', chapter: 16, verse: '9' },
    { book: '2 Chronicles', chapter: 20, verse: '15' },
    { book: 'Ezra', chapter: 8, verse: '22' },
    { book: 'Nehemiah', chapter: 1, verse: '5' },
    { book: 'Nehemiah', chapter: 8, verse: '10' },
    { book: 'Esther', chapter: 4, verse: '14' },
    { book: 'Job', chapter: 1, verse: '21' },
    { book: 'Job', chapter: 5, verse: '9' },
    { book: 'Job', chapter: 19, verse: '25' },
    { book: 'Job', chapter: 23, verse: '10' },
    { book: 'Job', chapter: 37, verse: '5' },
    { book: 'Job', chapter: 42, verse: '2' },
    { book: 'Psalms', chapter: 1, verse: '1-2' },
    { book: 'Psalms', chapter: 3, verse: '3' },
    { book: 'Psalms', chapter: 4, verse: '8' },
    { book: 'Psalms', chapter: 5, verse: '3' },
    { book: 'Psalms', chapter: 8, verse: '3-4' },
    { book: 'Psalms', chapter: 9, verse: '9' },
    { book: 'Psalms', chapter: 16, verse: '11' },
    { book: 'Psalms', chapter: 18, verse: '2' },
    { book: 'Psalms', chapter: 19, verse: '1' },
    { book: 'Psalms', chapter: 19, verse: '14' },
    { book: 'Psalms', chapter: 20, verse: '7' },
    { book: 'Psalms', chapter: 23, verse: '1' },
    { book: 'Psalms', chapter: 23, verse: '4' },
    { book: 'Psalms', chapter: 23, verse: '6' },
    { book: 'Psalms', chapter: 27, verse: '1' },
    { book: 'Psalms', chapter: 27, verse: '4' },
    { book: 'Psalms', chapter: 27, verse: '14' },
    { book: 'Psalms', chapter: 28, verse: '7' },
    { book: 'Psalms', chapter: 30, verse: '5' },
    { book: 'Psalms', chapter: 31, verse: '24' },
    { book: 'Psalms', chapter: 32, verse: '8' },
    { book: 'Psalms', chapter: 33, verse: '20' },
    { book: 'Psalms', chapter: 34, verse: '8' },
    { book: 'Psalms', chapter: 34, verse: '18' },
    { book: 'Psalms', chapter: 37, verse: '4' },
    { book: 'Psalms', chapter: 37, verse: '5' },
    { book: 'Psalms', chapter: 40, verse: '1-2' },
    { book: 'Psalms', chapter: 42, verse: '1-2' },
    { book: 'Psalms', chapter: 46, verse: '1' },
    { book: 'Psalms', chapter: 46, verse: '10' },
    { book: 'Psalms', chapter: 51, verse: '10' },
    { book: 'Psalms', chapter: 55, verse: '22' },
    { book: 'Psalms', chapter: 62, verse: '1-2' },
    { book: 'Psalms', chapter: 63, verse: '1' },
    { book: 'Psalms', chapter: 73, verse: '26' },
    { book: 'Psalms', chapter: 84, verse: '11' },
    { book: 'Psalms', chapter: 90, verse: '12' },
    { book: 'Psalms', chapter: 91, verse: '1-2' },
    { book: 'Psalms', chapter: 94, verse: '19' },
    { book: 'Psalms', chapter: 103, verse: '1-2' },
    { book: 'Psalms', chapter: 118, verse: '24' },
    { book: 'Psalms', chapter: 119, verse: '11' },
    { book: 'Psalms', chapter: 119, verse: '105' },
    { book: 'Psalms', chapter: 121, verse: '1-2' },
    { book: 'Psalms', chapter: 126, verse: '5' },
    { book: 'Psalms', chapter: 130, verse: '5' },
    { book: 'Psalms', chapter: 139, verse: '13-14' },
    { book: 'Psalms', chapter: 139, verse: '23-24' },
    { book: 'Psalms', chapter: 143, verse: '8' },
    { book: 'Psalms', chapter: 145, verse: '18' },
    { book: 'Psalms', chapter: 147, verse: '3' },
    { book: 'Proverbs', chapter: 1, verse: '7' },
    { book: 'Proverbs', chapter: 2, verse: '6' },
    { book: 'Proverbs', chapter: 3, verse: '5' },
    { book: 'Proverbs', chapter: 3, verse: '6' },
    { book: 'Proverbs', chapter: 3, verse: '9-10' },
    { book: 'Proverbs', chapter: 4, verse: '23' },
    { book: 'Proverbs', chapter: 8, verse: '11' },
    { book: 'Proverbs', chapter: 10, verse: '12' },
    { book: 'Proverbs', chapter: 11, verse: '14' },
    { book: 'Proverbs', chapter: 12, verse: '25' },
    { book: 'Proverbs', chapter: 13, verse: '20' },
    { book: 'Proverbs', chapter: 15, verse: '1' },
    { book: 'Proverbs', chapter: 16, verse: '3' },
    { book: 'Proverbs', chapter: 16, verse: '9' },
    { book: 'Proverbs', chapter: 17, verse: '17' },
    { book: 'Proverbs', chapter: 18, verse: '10' },
    { book: 'Proverbs', chapter: 18, verse: '24' },
    { book: 'Proverbs', chapter: 19, verse: '21' },
    { book: 'Proverbs', chapter: 22, verse: '6' },
    { book: 'Proverbs', chapter: 27, verse: '17' },
    { book: 'Proverbs', chapter: 28, verse: '13' },
    { book: 'Proverbs', chapter: 31, verse: '30' },
    { book: 'Ecclesiastes', chapter: 3, verse: '1' },
    { book: 'Ecclesiastes', chapter: 3, verse: '11' },
    { book: 'Ecclesiastes', chapter: 4, verse: '9-10' },
    { book: 'Ecclesiastes', chapter: 4, verse: '12' },
    { book: 'Ecclesiastes', chapter: 7, verse: '8' },
    { book: 'Ecclesiastes', chapter: 12, verse: '13' },
    { book: 'Song of Solomon', chapter: 2, verse: '4' },
    { book: 'Song of Solomon', chapter: 6, verse: '3' },
    { book: 'Song of Solomon', chapter: 8, verse: '7' },
    { book: 'Isaiah', chapter: 1, verse: '18' },
    { book: 'Isaiah', chapter: 6, verse: '8' },
    { book: 'Isaiah', chapter: 9, verse: '6' },
    { book: 'Isaiah', chapter: 12, verse: '2' },
    { book: 'Isaiah', chapter: 25, verse: '1' },
    { book: 'Isaiah', chapter: 26, verse: '3' },
    { book: 'Isaiah', chapter: 30, verse: '21' },
    { book: 'Isaiah', chapter: 40, verse: '8' },
    { book: 'Isaiah', chapter: 40, verse: '29' },
    { book: 'Isaiah', chapter: 40, verse: '31' },
    { book: 'Isaiah', chapter: 41, verse: '10' },
    { book: 'Isaiah', chapter: 41, verse: '13' },
    { book: 'Isaiah', chapter: 43, verse: '1' },
    { book: 'Isaiah', chapter: 43, verse: '2' },
    { book: 'Isaiah', chapter: 43, verse: '19' },
    { book: 'Isaiah', chapter: 46, verse: '4' },
    { book: 'Isaiah', chapter: 53, verse: '5' },
    { book: 'Isaiah', chapter: 53, verse: '6' },
    { book: 'Isaiah', chapter: 55, verse: '8-9' },
    { book: 'Isaiah', chapter: 55, verse: '11' },
    { book: 'Isaiah', chapter: 58, verse: '11' },
    { book: 'Isaiah', chapter: 61, verse: '1' },
    { book: 'Jeremiah', chapter: 1, verse: '5' },
    { book: 'Jeremiah', chapter: 9, verse: '23-24' },
    { book: 'Jeremiah', chapter: 17, verse: '7-8' },
    { book: 'Jeremiah', chapter: 23, verse: '24' },
    { book: 'Jeremiah', chapter: 29, verse: '11' },
    { book: 'Jeremiah', chapter: 29, verse: '13' },
    { book: 'Jeremiah', chapter: 31, verse: '3' },
    { book: 'Jeremiah', chapter: 32, verse: '17' },
    { book: 'Jeremiah', chapter: 32, verse: '27' },
    { book: 'Jeremiah', chapter: 33, verse: '3' },
    { book: 'Lamentations', chapter: 3, verse: '22-23' },
    { book: 'Lamentations', chapter: 3, verse: '24' },
    { book: 'Lamentations', chapter: 3, verse: '25' },
    { book: 'Ezekiel', chapter: 11, verse: '19' },
    { book: 'Ezekiel', chapter: 34, verse: '12' },
    { book: 'Ezekiel', chapter: 36, verse: '26' },
    { book: 'Ezekiel', chapter: 37, verse: '5' },
    { book: 'Ezekiel', chapter: 37, verse: '27' },
    { book: 'Daniel', chapter: 2, verse: '20' },
    { book: 'Daniel', chapter: 3, verse: '17' },
    { book: 'Daniel', chapter: 6, verse: '26' },
    { book: 'Daniel', chapter: 9, verse: '9' },
    { book: 'Daniel', chapter: 12, verse: '3' },
    { book: 'Hosea', chapter: 6, verse: '3' },
    { book: 'Hosea', chapter: 6, verse: '6' },
    { book: 'Joel', chapter: 2, verse: '13' },
    { book: 'Joel', chapter: 2, verse: '32' },
    { book: 'Amos', chapter: 5, verse: '14' },
    { book: 'Amos', chapter: 5, verse: '24' },
    { book: 'Obadiah', chapter: 1, verse: '15' },
    { book: 'Jonah', chapter: 2, verse: '7' },
    { book: 'Jonah', chapter: 2, verse: '9' },
    { book: 'Micah', chapter: 6, verse: '8' },
    { book: 'Micah', chapter: 7, verse: '7' },
    { book: 'Micah', chapter: 7, verse: '18' },
    { book: 'Nahum', chapter: 1, verse: '7' },
    { book: 'Habakkuk', chapter: 2, verse: '14' },
    { book: 'Habakkuk', chapter: 3, verse: '18' },
    { book: 'Zephaniah', chapter: 3, verse: '17' },
    { book: 'Zephaniah', chapter: 3, verse: '19' },
    { book: 'Haggai', chapter: 2, verse: '9' },
    { book: 'Zechariah', chapter: 4, verse: '6' },
    { book: 'Zechariah', chapter: 9, verse: '9' },
    { book: 'Zechariah', chapter: 13, verse: '9' },
    { book: 'Malachi', chapter: 3, verse: '6' },
    { book: 'Malachi', chapter: 3, verse: '10' },
    // New Testament
    { book: 'Matthew', chapter: 4, verse: '4' },
    { book: 'Matthew', chapter: 5, verse: '4' },
    { book: 'Matthew', chapter: 5, verse: '6' },
    { book: 'Matthew', chapter: 5, verse: '9' },
    { book: 'Matthew', chapter: 5, verse: '16' },
    { book: 'Matthew', chapter: 5, verse: '44' },
    { book: 'Matthew', chapter: 6, verse: '21' },
    { book: 'Matthew', chapter: 6, verse: '24' },
    { book: 'Matthew', chapter: 6, verse: '33' },
    { book: 'Matthew', chapter: 6, verse: '34' },
    { book: 'Matthew', chapter: 7, verse: '7' },
    { book: 'Matthew', chapter: 7, verse: '12' },
    { book: 'Matthew', chapter: 11, verse: '28' },
    { book: 'Matthew', chapter: 11, verse: '29-30' },
    { book: 'Matthew', chapter: 16, verse: '24' },
    { book: 'Matthew', chapter: 19, verse: '26' },
    { book: 'Matthew', chapter: 22, verse: '37-38' },
    { book: 'Matthew', chapter: 22, verse: '39' },
    { book: 'Matthew', chapter: 28, verse: '19' },
    { book: 'Matthew', chapter: 28, verse: '20' },
    { book: 'Mark', chapter: 8, verse: '36' },
    { book: 'Mark', chapter: 9, verse: '23' },
    { book: 'Mark', chapter: 10, verse: '27' },
    { book: 'Mark', chapter: 10, verse: '45' },
    { book: 'Mark', chapter: 11, verse: '24' },
    { book: 'Mark', chapter: 12, verse: '30' },
    { book: 'Mark', chapter: 12, verse: '31' },
    { book: 'Mark', chapter: 16, verse: '15' },
    { book: 'Luke', chapter: 1, verse: '37' },
    { book: 'Luke', chapter: 2, verse: '11' },
    { book: 'Luke', chapter: 6, verse: '31' },
    { book: 'Luke', chapter: 6, verse: '37' },
    { book: 'Luke', chapter: 6, verse: '38' },
    { book: 'Luke', chapter: 9, verse: '23' },
    { book: 'Luke', chapter: 11, verse: '9' },
    { book: 'Luke', chapter: 12, verse: '15' },
    { book: 'Luke', chapter: 12, verse: '34' },
    { book: 'Luke', chapter: 18, verse: '27' },
    { book: 'Luke', chapter: 21, verse: '33' },
    { book: 'John', chapter: 1, verse: '1' },
    { book: 'John', chapter: 1, verse: '14' },
    { book: 'John', chapter: 3, verse: '16' },
    { book: 'John', chapter: 3, verse: '17' },
    { book: 'John', chapter: 6, verse: '35' },
    { book: 'John', chapter: 8, verse: '12' },
    { book: 'John', chapter: 8, verse: '32' },
    { book: 'John', chapter: 10, verse: '10' },
    { book: 'John', chapter: 10, verse: '11' },
    { book: 'John', chapter: 11, verse: '25' },
    { book: 'John', chapter: 13, verse: '34' },
    { book: 'John', chapter: 14, verse: '1' },
    { book: 'John', chapter: 14, verse: '6' },
    { book: 'John', chapter: 14, verse: '27' },
    { book: 'John', chapter: 15, verse: '5' },
    { book: 'John', chapter: 15, verse: '13' },
    { book: 'John', chapter: 16, verse: '33' },
    { book: 'John', chapter: 20, verse: '29' },
    { book: 'Acts', chapter: 1, verse: '8' },
    { book: 'Acts', chapter: 2, verse: '38' },
    { book: 'Acts', chapter: 3, verse: '19' },
    { book: 'Acts', chapter: 4, verse: '12' },
    { book: 'Acts', chapter: 16, verse: '31' },
    { book: 'Acts', chapter: 17, verse: '28' },
    { book: 'Acts', chapter: 20, verse: '35' },
    { book: 'Romans', chapter: 1, verse: '16' },
    { book: 'Romans', chapter: 3, verse: '23' },
    { book: 'Romans', chapter: 5, verse: '1' },
    { book: 'Romans', chapter: 5, verse: '8' },
    { book: 'Romans', chapter: 6, verse: '23' },
    { book: 'Romans', chapter: 8, verse: '1' },
    { book: 'Romans', chapter: 8, verse: '18' },
    { book: 'Romans', chapter: 8, verse: '26' },
    { book: 'Romans', chapter: 8, verse: '28' },
    { book: 'Romans', chapter: 8, verse: '31' },
    { book: 'Romans', chapter: 8, verse: '38-39' },
    { book: 'Romans', chapter: 10, verse: '9' },
    { book: 'Romans', chapter: 10, verse: '17' },
    { book: 'Romans', chapter: 12, verse: '1' },
    { book: 'Romans', chapter: 12, verse: '2' },
    { book: 'Romans', chapter: 12, verse: '12' },
    { book: 'Romans', chapter: 15, verse: '13' },
    { book: '1 Corinthians', chapter: 1, verse: '18' },
    { book: '1 Corinthians', chapter: 2, verse: '9' },
    { book: '1 Corinthians', chapter: 6, verse: '19-20' },
    { book: '1 Corinthians', chapter: 10, verse: '13' },
    { book: '1 Corinthians', chapter: 10, verse: '31' },
    { book: '1 Corinthians', chapter: 13, verse: '4' },
    { book: '1 Corinthians', chapter: 13, verse: '7' },
    { book: '1 Corinthians', chapter: 13, verse: '13' },
    { book: '1 Corinthians', chapter: 15, verse: '57' },
    { book: '1 Corinthians', chapter: 15, verse: '58' },
    { book: '1 Corinthians', chapter: 16, verse: '13' },
    { book: '1 Corinthians', chapter: 16, verse: '14' },
    { book: '2 Corinthians', chapter: 1, verse: '3-4' },
    { book: '2 Corinthians', chapter: 4, verse: '16' },
    { book: '2 Corinthians', chapter: 4, verse: '18' },
    { book: '2 Corinthians', chapter: 5, verse: '7' },
    { book: '2 Corinthians', chapter: 5, verse: '17' },
    { book: '2 Corinthians', chapter: 9, verse: '7' },
    { book: '2 Corinthians', chapter: 12, verse: '9' },
    { book: 'Galatians', chapter: 2, verse: '20' },
    { book: 'Galatians', chapter: 5, verse: '1' },
    { book: 'Galatians', chapter: 5, verse: '22-23' },
    { book: 'Galatians', chapter: 6, verse: '2' },
    { book: 'Galatians', chapter: 6, verse: '9' },
    { book: 'Ephesians', chapter: 1, verse: '7' },
    { book: 'Ephesians', chapter: 2, verse: '8-9' },
    { book: 'Ephesians', chapter: 2, verse: '10' },
    { book: 'Ephesians', chapter: 3, verse: '20' },
    { book: 'Ephesians', chapter: 4, verse: '2' },
    { book: 'Ephesians', chapter: 4, verse: '32' },
    { book: 'Ephesians', chapter: 5, verse: '2' },
    { book: 'Ephesians', chapter: 6, verse: '10' },
    { book: 'Ephesians', chapter: 6, verse: '11' },
    { book: 'Ephesians', chapter: 6, verse: '18' },
    { book: 'Philippians', chapter: 1, verse: '6' },
    { book: 'Philippians', chapter: 2, verse: '3' },
    { book: 'Philippians', chapter: 2, verse: '4' },
    { book: 'Philippians', chapter: 3, verse: '14' },
    { book: 'Philippians', chapter: 4, verse: '4' },
    { book: 'Philippians', chapter: 4, verse: '6' },
    { book: 'Philippians', chapter: 4, verse: '7' },
    { book: 'Philippians', chapter: 4, verse: '8' },
    { book: 'Philippians', chapter: 4, verse: '13' },
    { book: 'Philippians', chapter: 4, verse: '19' },
    { book: 'Colossians', chapter: 1, verse: '17' },
    { book: 'Colossians', chapter: 3, verse: '2' },
    { book: 'Colossians', chapter: 3, verse: '12' },
    { book: 'Colossians', chapter: 3, verse: '16' },
    { book: 'Colossians', chapter: 3, verse: '23' },
    { book: '1 Thessalonians', chapter: 4, verse: '16-17' },
    { book: '1 Thessalonians', chapter: 5, verse: '11' },
    { book: '1 Thessalonians', chapter: 5, verse: '16-18' },
    { book: '2 Thessalonians', chapter: 3, verse: '3' },
    { book: '2 Thessalonians', chapter: 3, verse: '16' },
    { book: '1 Timothy', chapter: 4, verse: '12' },
    { book: '1 Timothy', chapter: 6, verse: '6' },
    { book: '1 Timothy', chapter: 6, verse: '12' },
    { book: '2 Timothy', chapter: 1, verse: '7' },
    { book: '2 Timothy', chapter: 2, verse: '15' },
    { book: '2 Timothy', chapter: 3, verse: '16' },
    { book: '2 Timothy', chapter: 4, verse: '7' },
    { book: 'Titus', chapter: 3, verse: '5' },
    { book: 'Philemon', chapter: 1, verse: '6' },
    { book: 'Hebrews', chapter: 4, verse: '12' },
    { book: 'Hebrews', chapter: 4, verse: '16' },
    { book: 'Hebrews', chapter: 10, verse: '23' },
    { book: 'Hebrews', chapter: 10, verse: '24-25' },
    { book: 'Hebrews', chapter: 11, verse: '1' },
    { book: 'Hebrews', chapter: 11, verse: '6' },
    { book: 'Hebrews', chapter: 12, verse: '1' },
    { book: 'Hebrews', chapter: 12, verse: '2' },
    { book: 'Hebrews', chapter: 13, verse: '5' },
    { book: 'Hebrews', chapter: 13, verse: '8' },
    { book: 'James', chapter: 1, verse: '2-3' },
    { book: 'James', chapter: 1, verse: '5' },
    { book: 'James', chapter: 1, verse: '12' },
    { book: 'James', chapter: 1, verse: '17' },
    { book: 'James', chapter: 1, verse: '22' },
    { book: 'James', chapter: 4, verse: '7' },
    { book: 'James', chapter: 5, verse: '16' },
    { book: '1 Peter', chapter: 1, verse: '3' },
    { book: '1 Peter', chapter: 2, verse: '9' },
    { book: '1 Peter', chapter: 3, verse: '15' },
    { book: '1 Peter', chapter: 4, verse: '8' },
    { book: '1 Peter', chapter: 4, verse: '10' },
    { book: '1 Peter', chapter: 5, verse: '7' },
    { book: '1 Peter', chapter: 5, verse: '8' },
    { book: '2 Peter', chapter: 1, verse: '3' },
    { book: '2 Peter', chapter: 3, verse: '9' },
    { book: '1 John', chapter: 1, verse: '9' },
    { book: '1 John', chapter: 3, verse: '1' },
    { book: '1 John', chapter: 3, verse: '16' },
    { book: '1 John', chapter: 4, verse: '7' },
    { book: '1 John', chapter: 4, verse: '9-10' },
    { book: '1 John', chapter: 4, verse: '18' },
    { book: '1 John', chapter: 4, verse: '19' },
    { book: '1 John', chapter: 5, verse: '14' },
    { book: '2 John', chapter: 1, verse: '6' },
    { book: '3 John', chapter: 1, verse: '4' },
    { book: 'Jude', chapter: 1, verse: '20-21' },
    { book: 'Jude', chapter: 1, verse: '24-25' },
    { book: 'Revelation', chapter: 1, verse: '8' },
    { book: 'Revelation', chapter: 3, verse: '20' },
    { book: 'Revelation', chapter: 5, verse: '12' },
    { book: 'Revelation', chapter: 7, verse: '17' },
    { book: 'Revelation', chapter: 21, verse: '4' },
    { book: 'Revelation', chapter: 21, verse: '5' },
    { book: 'Revelation', chapter: 22, verse: '13' },
    { book: 'Revelation', chapter: 22, verse: '20' },
  ];

  isLeapYear(year) {
    return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
  }

  getDayOfYear(date) {
    const startOfYear = new Date(date.getFullYear(), 0, 1);
    return Math.floor((date - startOfYear) / 86400000); // 0 on Jan 1
  }

  // Returns the curated verse reference for a given date.
  // mode: 'daily'  -> advances once per day
  //       'weekly' -> advances once per week (stable across the week)
  // The whole list is mapped across the year, so both modes walk from
  // Genesis in January toward Revelation in December.
  getVerseOfDay(date = new Date(), mode = 'daily') {
    const list = this.VERSES_OF_THE_DAY;
    if (!list.length) return null;

    const dayOfYear = this.getDayOfYear(date);

    let fraction;
    if (mode === 'weekly') {
      fraction = Math.floor(dayOfYear / 7) / 53;
    } else {
      const daysInYear = this.isLeapYear(date.getFullYear()) ? 366 : 365;
      fraction = dayOfYear / daysInYear;
    }

    let index = Math.floor(fraction * list.length);
    index = Math.max(0, Math.min(list.length - 1, index));

    const entry = list[index];
    return {
      ...entry,
      index,
      mode,
      reference: `${entry.book} ${entry.chapter}:${entry.verse}`,
    };
  }

  bibleBooks = {
    'Old Testament': [
      'Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy',
      'Joshua', 'Judges', 'Ruth', '1 Samuel', '2 Samuel',
      '1 Kings', '2 Kings', '1 Chronicles', '2 Chronicles',
      'Ezra', 'Nehemiah', 'Esther', 'Job', 'Psalms', 'Proverbs',
      'Ecclesiastes', 'Song of Solomon', 'Isaiah', 'Jeremiah',
      'Lamentations', 'Ezekiel', 'Daniel', 'Hosea', 'Joel',
      'Amos', 'Obadiah', 'Jonah', 'Micah', 'Nahum', 'Habakkuk',
      'Zephaniah', 'Haggai', 'Zechariah', 'Malachi'
    ],
    'New Testament': [
      'Matthew', 'Mark', 'Luke', 'John', 'Acts', 'Romans',
      '1 Corinthians', '2 Corinthians', 'Galatians', 'Ephesians',
      'Philippians', 'Colossians', '1 Thessalonians', '2 Thessalonians',
      '1 Timothy', '2 Timothy', 'Titus', 'Philemon', 'Hebrews',
      'James', '1 Peter', '2 Peter', '1 John', '2 John', '3 John',
      'Jude', 'Revelation'
    ]
  };
  
  abbrvBooks = {
    'Gen': 'Genesis', 'Exod': 'Exodus', 'Lev': 'Leviticus', 'Num': 'Numbers', 'Deut': 'Deuteronomy',
    'Josh': 'Joshua', 'Judg': 'Judges', 'Ruth': 'Ruth', '1 Sam': '1 Samuel', '2 Sam': '2 Samuel',
    '1 Kgs': '1 Kings', '2 Kgs': '2 Kings', '1 Chr': '1 Chronicles', '2 Chr': '2 Chronicles',
    'Ezra': 'Ezra', 'Neh': 'Nehemiah', 'Esth': 'Esther', 'Job': 'Job', 'Ps': 'Psalms',
    'Prov': 'Proverbs', 'Eccl': 'Ecclesiastes', 'Song': 'Song of Solomon', 'Isa': 'Isaiah',
    'Jer': 'Jeremiah', 'Lam': 'Lamentations', 'Ezek': 'Ezekiel', 'Dan': 'Daniel',
    'Hos': 'Hosea', 'Joel': 'Joel', 'Amos': 'Amos', 'Obad': 'Obadiah', 'Jonah': 'Jonah',
    'Mic': 'Micah', 'Nah': 'Nahum', 'Hab': 'Habakkuk', 'Zeph': 'Zephaniah', 'Hag': 'Haggai',
    'Zech': 'Zechariah', 'Mal': 'Malachi', 'Matt': 'Matthew', 'Mark': 'Mark',
    'Luke': 'Luke', 'John': 'John', 'Acts': 'Acts', 'Rom': 'Romans', '1 Cor': '1 Corinthians', '2 Cor': '2 Corinthians',
    'Gal': 'Galatians', 'Eph': 'Ephesians', 'Phil': 'Philippians', 'Col': 'Colossians',
    '1 Thess': '1 Thessalonians', '2 Thess': '2 Thessalonians',
    '1 Tim': '1 Timothy', '2 Tim': '2 Timothy', 'Titus': 'Titus', 'Philem': 'Philemon',
    'Heb': 'Hebrews', 'Jas': 'James', '1 Pet': '1 Peter', '2 Pet': '2 Peter',
    '1 John': '1 John', '2 John': '2 John', '3 John': '3 John', 'Jude': 'Jude', 'Rev': 'Revelation'};

  chapterCounts = {
    'Genesis': 50, 'Exodus': 40, 'Leviticus': 27, 'Numbers': 36, 'Deuteronomy': 34,
    'Joshua': 24, 'Judges': 21, 'Ruth': 4, '1 Samuel': 31, '2 Samuel': 24,
    '1 Kings': 22, '2 Kings': 25, '1 Chronicles': 29, '2 Chronicles': 36,
    'Ezra': 10, 'Nehemiah': 13, 'Esther': 10, 'Job': 42, 'Psalms': 150,
    'Proverbs': 31, 'Ecclesiastes': 12, 'Song of Solomon': 8, 'Isaiah': 66,
    'Jeremiah': 52, 'Lamentations': 5, 'Ezekiel': 48, 'Daniel': 12,
    'Hosea': 14, 'Joel': 3, 'Amos': 9, 'Obadiah': 1, 'Jonah': 4,
    'Micah': 7, 'Nahum': 3, 'Habakkuk': 3, 'Zephaniah': 3, 'Haggai': 2,
    'Zechariah': 14, 'Malachi': 4, 'Matthew': 28, 'Mark': 16, 'Luke': 24,
    'John': 21, 'Acts': 28, 'Romans': 16, '1 Corinthians': 16,
    '2 Corinthians': 13, 'Galatians': 6, 'Ephesians': 6, 'Philippians': 4,
    'Colossians': 4, '1 Thessalonians': 5, '2 Thessalonians': 3,
    '1 Timothy': 6, '2 Timothy': 4, 'Titus': 3, 'Philemon': 1,
    'Hebrews': 13, 'James': 5, '1 Peter': 5, '2 Peter': 3,
    '1 John': 5, '2 John': 1, '3 John': 1, 'Jude': 1, 'Revelation': 22
  };

  translations = [
    { id: 'web', name: 'WEB' },
    { id: 'kjv', name: 'KJV' },
    { id: 'bbe', name: 'BBE' },
    { id: 'clementine', name: 'Vulgate' }
  ];

  // Flatten books list for searching
  allBooks = [...this.bibleBooks['Old Testament'], ...this.bibleBooks['New Testament'], ...Object.keys(this.abbrvBooks)];
}