name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: biblicalendar_app

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
